part_system_destroy(part_system);

part_type_destroy(part_type_exhaust);
part_type_destroy(part_type_enemy_exhaust);
part_type_destroy(part_type_asteroid_debris);
part_type_destroy(part_type_ship_debris);
part_type_destroy(part_type_bullet_debris);
